### ISSUE TITLE
This takes a while to produce the prompt.

### ISSUE THREAD

**Issue by jsharpminor** [jcgoble3/gitstuff#1]

**Comment by jcgoble3** [comment]
What operating system are you using? On my Windows machine, this indeed takes a second or two to produce the prompt, because it launches a number of new processes, and launching a new process is expensive in Windows. AFAIK, there is no workaround for that.

This is more designed for users of Unix OSes where it is cheap to launch a process; my Ubuntu machine produces the prompt instantly (i.e. no delay detectable by the unaided eye).

I have not tested this under the Windows Subsystem for Linux yet, however, so I do not know how fast or slow it is there.

**Comment by jsharpminor** [comment]
Yep, that'll be it. I'm using it  on Windows 7.

**Comment by jcgoble3** [comment]
Alright then. Since there's no way to work around this, I'm closing this issue.

**Comment by jsharpminor** [comment]
I don't know if this makes a difference to you, but I'm trying it with openSUSE and finding that I have the same issue. It's not as bad as on Windows, but there's clearly a noticeable delay.

**Comment by jcgoble3** [comment]
Sorry, I've been busy and couldn't reply right away. I know nothing at all about openSUSE, so I can't help you there. However, if you have a fix that improves the performance on that platform and/or on Windows, then I'll be happy to take a look at a pull request.
