### ISSUE TITLE
"P" does not show in Git Bash for Windows

### ISSUE THREAD

**Issue by ryanmenzer** [jcgoble3/gitstuff#4]
I'm running Windows 10 on a BootCamp partition on a 2017 MacbookPro Touchbar i7 16GB ram. I have successfully run this on OS X but in Windows, using Git Bash there is a bug:

Everything works except the "P" does not display at all when it should. I have tried both lines of code:
`[[ -n $(git log --branches --not --remotes) ]] && output="${output}P"`
`[[ -n $(git status -sb|grep -E "\[ahead .+\]") ]] && output="${output}P"`
Neither one will display the "P". 

Love it, otherwise!!! Thanks!

**Comment by jcgoble3** [comment]
I haven't used Git in Windows in a while, since Linux is now my daily driver. I fired up my Windows 10 VM in VirtualBox under Ubuntu 17.10 and tried this code in Git Bash for Windows by cloning this repo, creating a new file, and committing that file locally without pushing it. In both cases (both lines of code), the "P" displayed as expected for me.

My Git version (output of `git version`) is 2.14.1.windows.1, which is a little out of date. Can you tell me what your `git version` command outputs? I will give that version a try and see if I can reproduce the bug that way before spring break is over. Also, if you have the time, try running the commands in the parentheses directly and reporting whether there is any output, and if so, what that output is. (The "P" should display anytime the command produces output; no output should mean no unpushed changes.)

**Comment by ryanmenzer** [comment]
`git version` ==> 2.16.1.windows.4

I made a change, staged and committed it locally, and here are my results:

`git log --branches --not --remotes` ==> The log of the commit I just made, then a bunch of old commit logs from branches I haven't touched in while. When I quit out of the log list, no "P" is displayed, just the branch name.

`git status -sb|grep -E "\[ahead .+\]"` ==> Nothing, and no "P", just the branch name.

**Comment by jcgoble3** [comment]
I tried again with the same version of Git for Windows that you are using, and I am still unable to reproduce. The confusing part here is that somehow your `git log --branches --not --remotes` command is producing output but not triggering the "P"; the "P" should be triggered if anything at all is sent to standard output by the test command.

Try this: set the `git log...` command as the test in `.bashrc`, make sure the line is exactly as shown here, run `source ~/.bashrc`, then with an unpushed commit, run the same `git log...` command directly. If you get any output from the direct command but still do not get the "P", then my guess is that there is likely something wrong with or missing from your local code.

In that case, try commenting out all of your local "git prompt" code, pasting the code from this repo in directly and unmodified, and `source ~/.bashrc` and try again. If it works that time, the bug is in something you tweaked, either intentionally or accidentally.

If you still have the problem with the unmodified code, from a prompt showing the bug, and using the `git log...` test command in `.bashrc`, run `set -x` (to enable tracing) followed by `set +x` (to disable tracing). In between those commands, you should get a trace output of everything Bash ran to generate the prompt. Copy and paste that here (redacting if necessary, as names/email addresses may appear from a `git log`) and I'll take a look at it to see where the bug is.

(Aside: if the bug doesn't show with the unmodified code, try running the trace output anyway with both the unmodified code and your own code, and comparing them to see where they diverge. That ought to give you a clue as to where the bug is in that case.)

For the record, here is the trace output I get when failing to reproduce the bug:

```
++ git_prompt
+++ git_branch
+++ git branch --no-color
+++ sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
++ local branch=master
++ [[ -n master ]]
+++ git_status
++++ git status --porcelain
+++ local status=
+++ local output=
++++ egrep '^[MADRC]'
+++ [[ -n '' ]]
++++ egrep '^.[MD]'
+++ [[ -n '' ]]
++++ egrep '^\?\?'
+++ [[ -n '' ]]
++++ git stash list
+++ [[ -n '' ]]
++++ git log --branches --not --remotes
+++ [[ -n commit 178632e4a97efc671c5d52e54539b01cb68b2fc1
Author: Jonathan Goble <email redacted>
Date:   Thu Mar 15 15:30:56 2018 -0400

    test ]]
+++ output=P
+++ [[ -n P ]]
+++ output='|P'
+++ echo '|P'
++ local 'state=|P'
+++ git_color '|P'
++++ [[ |P =~ \+ ]]
+++ local staged=
++++ [[ |P =~ [!?] ]]
+++ local dirty=
++++ [[ |P =~ P ]]
++++ echo yes
+++ local needs_push=yes
+++ [[ -n '' ]]
+++ [[ -n '' ]]
+++ [[ -n '' ]]
+++ [[ -n yes ]]
+++ echo -e '\033[1;34m'
++ local 'color='
++ echo -e '\x01\x02[master|P]\x01\033[00m\x02'
```

**Comment by ryanmenzer** [comment]
One quick question before I follow your steps: 

I have all this code in .bash_profile, not .bashrc. I don't even have a .bashrc file. I'm assuming that cannot be the issue since there would just be a link in the .bash_profile to .bashrc; also, every other feature of this code is working (colors, other symbols, etc). This couldn't be the reason the "P" isn't showing up, right?

**Comment by jcgoble3** [comment]
No, that setup is perfectly fine. I prefer .bashrc being a regular Linux user, so my Windows .bash_profile does nothing but load .bashrc. But running it directly from .bash_profile is fine as well. So just substitute .bash_profile in everywhere you see .bashrc in my previous comment.

**Comment by ryanmenzer** [comment]
A clue surfaced out of the blue:

In git bash, I pulled down a branch from our remote repo to my local machine, made a change, committed the change locally, and the "P" showed up!  

I wonder if the branches that I create locally and then pushing to remote are not doing it properly. I switched back to a branch I created locally that is supposedly being tracked remotely, opened Visual Studio Team Explorer and it said: "The current branch does not track a remote branch. Push your changes to a new branch on the origin remote and set the upstream branch." 

I can clearly see my branch in our remote repo and see all the changes I commit and push using git bash. But maybe there's some setting that's not being configured regarding the "upstream" part?

My normal procedure for creating branches locally is` git checkout master`, `git checkout -b <branchname>`. After committing changes, I `git push origin <branchname>`. Anything wrong with that flow?

**Comment by jcgoble3** [comment]
> My normal procedure for creating branches locally is `git checkout master`, `git checkout -b <branchname>`. After committing changes, I `git push origin <branchname>`. Anything wrong with that flow?

The first time you push a new locally created branch, you need to explicitly set the upstream, otherwise your local Git doesn't know that the local branch should be tracking the remote branch you just created. The correct command is `git push --set-upstream origin <branchname>`, or `git push -u origin <branchname>` This is only needed on the first push of a new branch (or once if you haven't done it before); after that, the `-u`/`--set-upstream` is no longer needed. Unfortunately, `git help push` doesn't explain this very well.

Try setting the upstream as I just described and see if that solves your problem.

**Comment by ryanmenzer** [comment]
You confirmed what I just read, too. The upstream tracking was never set. It all works now! 

I'm still a junior dev but I don't know why git wouldn't automatically track a newly pushed branch. Isn't that the whole point of having a remote repo?

**Comment by jcgoble3** [comment]
I'm still a freshman computer science college student, so I don't get it either. :stuck_out_tongue: But it doesn't, so you have to remember to do it yourself.

Glad we found the problem! :smiley:
